# Generated by Django 3.2.5 on 2021-09-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='generation',
            new_name='value',
        ),
    ]
