# Generated by Django 3.2.5 on 2021-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0002_rename_generation_generation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='idClient',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='minDistance',
            field=models.IntegerField(default=-1),
        ),
    ]
