# Generated by Django 3.2.5 on 2021-09-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0003_auto_20210922_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='balls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='endX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='endY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='walls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
