# Generated by Django 3.2.5 on 2021-09-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0004_auto_20210922_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.IntegerField(primary_key=True, serialize=False)),
                ('population', models.IntegerField()),
                ('incLean', models.BooleanField()),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('win', models.BooleanField(default=False)),
                ('stopThread', models.BooleanField(default=False)),
                ('minDistance', models.IntegerField(default=-1)),
                ('map', models.JSONField(blank=True, null=True)),
                ('walls', models.JSONField(blank=True, null=True)),
                ('balls', models.JSONField(blank=True, null=True)),
                ('endX', models.IntegerField(blank=True, null=True)),
                ('endY', models.IntegerField(blank=True, null=True)),
                ('possibleMov', models.IntegerField(default=40)),
                ('cicleToRemove', models.IntegerField(default=30)),
                ('cicleToDecrease', models.IntegerField(default=90)),
            ],
        ),
        migrations.AlterField(
            model_name='generation',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeatAiApp.client'),
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
