# Generated by Django 3.2.5 on 2021-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0006_remove_client_walls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='win',
        ),
        migrations.AddField(
            model_name='generation',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
