# Generated by Django 3.2.5 on 2021-10-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0007_auto_20210925_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='finishedThread',
            field=models.BooleanField(default=False),
        ),
    ]
