# Generated by Django 3.2.5 on 2021-11-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0008_client_finishedthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lenghtMap',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
