# Generated by Django 3.2.5 on 2021-11-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0009_client_lenghtmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pathFind',
            field=models.BooleanField(null=True),
        ),
    ]
