# Generated by Django 3.2.5 on 2021-11-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatAiApp', '0010_client_pathfind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cicleToDecrease',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='cicleToRemove',
            field=models.IntegerField(default=90),
        ),
    ]
